export THEOS_DEVICE_IP=devpod.local

include theos/makefiles/common.mk

TWEAK_NAME = TabCleaner
TabCleaner_FILES = Tweak.xm
TabCleaner_FRAMEWORKS = UIKit
KILL_APP = MobileSafari

include $(THEOS_MAKE_PATH)/tweak.mk
